### PR TITLE
Clearly distinguish factored width from the tree width

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
@St333p so do you agree with the changes? This blocks the release cycle, we need to take a decision on whether to merge this PR ASAP

**Review by St333p — APPROVED** [review]
I don't have a strong opinion on these changes, so I guess you can merge it

**Review by zoedberg — COMMENTED** [review]
I also don't have a strong opinion on the changed code.

I'm not sure why `Merklization.svg` shows an incomplete tree while `MPC.svg` shows a complete one. I think that without a proper description of the images they are not very useful and could cause some doubts. Could you please clarify this and maybe explain the meaning of the graphs in the crate's README?

**Comment by dr-orlovsky** [comment]
> I'm not sure why Merklization.svg shows an incomplete tree while MPC.svg shows a complete one.

merklization.svg describes what merkle.rs module is doing, and MPC is what mpc module is doing - two different procedures.

> Could you please clarify this and maybe explain the meaning of the graphs in the crate's README?

The graphs are not referenced and included in the README, I have to re-write it. I think this should be a dedicated PR unrelated to this one.

**Comment by zoedberg** [comment]
Ok, then this PR can be merged

**Review by zoedberg — APPROVED** [review]

**Pull request merged**
