### PR TITLE
Update to the most recent bitcoin, miniscript and other dependencies

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Comment by zoedberg** [comment]
I'll review this PR once the 0.8.x milestone will be completed because right now if I try to switch to this branch (or to `master`) rgb-lib tests (which are my main reference when reviewing code changes) don't compile.

**Comment by zoedberg** [comment]
@dr-orlovsky I've seen you are merging fixes in a `v0.8` branch, good idea! Maybe it makes sense to rebase this PR on that branch? It would be nice to have `0.8.x` stack using rust-bitcoin `0.29.x`

**Comment by dr-orlovsky** [comment]
It is not possible, since updating dependency to a breaking change is always a breaking change, i.e. we can't have 0.29 in 0.8 in any way.

**Comment by cryptoquick** [comment]
Agreed!

**Pull request merged**
