### PR TITLE
Fix merkle proof conversion

### PR DESCRIPTION
**Pull request by crisdut**
Details: https://github.com/LNP-BP/client_side_validation/pull/103#issuecomment-1321213601

### CODE REVIEW

**Review by dr-orlovsky — APPROVED** [review]
ACK https://github.com/LNP-BP/client_side_validation/commit/a3c3f1d95dd4895838258feb85e82e2881904bd3

**Review by zoedberg — APPROVED** [review]
ACK 02167b9 (commit merged in v0.8, currently I cannot test v0.9)

**Comment by dr-orlovsky** [comment]
@crisdut I can't merge because of this stupid clippy which found something in the CI. Can you pls push another commit which fixes this so I can merge the PR?
https://github.com/LNP-BP/client_side_validation/actions/runs/3509424205/jobs/5878511132#step:4:250

**Review by dr-orlovsky — APPROVED** [review]
ACK 7bde82662f841fc77d4e60fba3906bdefa5f35f3

**Pull request merged**
