### PR TITLE
update MSRV to 1.76 (due to ascii-armor)

### PR DESCRIPTION
**Pull request by zoedberg**

### CODE REVIEW

**Comment by zoedberg** [comment]
I'm trying to understand why the `testing (macos-13)` job fails. @dr-orlovsky have you ever encountered such issue?

**Comment by zoedberg** [comment]
It seems it was just a temporary issue. I don't understand why there's an expected check still called `toolchains (1.75.0)` though, @dr-orlovsky do you have any idea? Apart from that this PR can be merged

**Comment by dr-orlovsky** [comment]
> I'm trying to understand why the testing (macos-13) job fails. @dr-orlovsky have you ever encountered such issue?

Yes, all the time. It seems github has a low availability of apple silicon machines and fequently CI hangs on macos-13 (as well as windows sometimes).

>  an expected check still called toolchains (1.75.0)

It should be changed in the branch rules in settings. Doing that.

**Review by dr-orlovsky — APPROVED** [review]
ACK 0d2f818850588c839b02b50ac8fc8d98e5d431af

**Pull request merged**
